version: '3'

services:
  php:
    container_name: php_webpage
    build: ./docker/php
    restart: always
    volumes:
      - ./:/var/www

  nginx:
    image: nginx
    container_name: nginx_webpage
    restart: always
    ports:
      - 8080:80
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  mysql:
    image: mysql:5.7
    container_name: db_webpage
    restart: always
    tty: true
    ports:
      - 4406:3306
    environment:
      MYSQL_DATABASE: db_webpage #DB名はアンダーバーでもハイフンで認識されるようです。.envのDB名では-を使って書かないとエラーが生じます。
      MYSQL_USER: webpage
      MYSQL_PASSWORD: password 
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - db:/var/lib/mysql

volumes:
  db:

